### ISSUE TITLE
Unable to publish with Java 10+

### ISSUE THREAD

**Issue by szpak** [gradle-nexus/publish-plugin#15]
Trying to publish the plugin (even to the local Maven repository) fails with Java 11 (and 13):
```
$ gw publishToMavenLocal

> Task :dokka
logging: loading modules: [java.se, jdk.accessibility, jdk.attach, jdk.compiler, jdk.dynalink, jdk.httpserver, jdk.jartool, jdk.javadoc, jdk.jconsole, jdk.jdi, jdk.jfr, jdk.jshell, jdk.jsobject, jdk.management, jdk.management.jfr, jdk.net, jdk.scripting.nashorn, jdk.sctp, jdk.security.auth, jdk.security.jgss, jdk.unsupported, jdk.unsupported.desktop, jdk.xml.dom, java.base, java.compiler, java.datatransfer, java.desktop, java.xml, java.instrument, java.logging, java.management, java.management.rmi, java.rmi, java.naming, java.net.http, java.prefs, java.scripting, java.security.jgss, java.security.sasl, java.sql, java.transaction.xa, java.sql.rowset, java.xml.crypto, jdk.internal.jvmstat, jdk.management.agent, jdk.jdwp.agent, jdk.internal.ed, jdk.internal.le, jdk.internal.opt]

> Task :dokka FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dokka'.
> com/sun/tools/doclets/formats/html/HtmlDoclet
```

It seems to be a known [issue](https://github.com/Kotlin/dokka/issues/294) with dokka and Java 10+. While the plugin is Java 8 compatible and we can release with Java 8, it is definitely something to take a look at (any alternative to dokka?) as many people locally by default use Java 11 (or 13) and it would be nice to do not fail with it.

Longer stacktrace:
```
* What went wrong:
Execution failed for task ':dokka'.
> com/sun/tools/doclets/formats/html/HtmlDoclet

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dokka'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:187)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:185)
...
Caused by: java.lang.NoClassDefFoundError: com/sun/tools/doclets/formats/html/HtmlDoclet
        at org.jetbrains.dokka.javadoc.JavadocGenerator.buildPages(dokka-adapters.kt:19)
        at org.jetbrains.dokka.GeneratorKt.buildAll(Generator.kt:13)
        at org.jetbrains.dokka.GeneratorKt.buildAll(Generator.kt:23)
        at org.jetbrains.dokka.DokkaGenerator.generate(DokkaGenerator.kt:52)
        at org.jetbrains.dokka.DokkaBootstrapImpl.generate(DokkaBootstrapImpl.kt:75)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.jetbrains.dokka.gradle.DelegatedInvocationHandler.invoke(ProxyUtils.kt:41)
        at com.sun.proxy.$Proxy144.generate(Unknown Source)
        at org.jetbrains.dokka.gradle.DokkaTask.generate(DokkaTask.kt:177)
...
```

**Comment by marcphilipp** [comment]
I absolutely agree and find the lack of Java 11 support of dokka really strange. I don't know of an alternative, though.

**Comment by marcphilipp** [comment]
I've upgraded Dokka in 8b08aaef87b07a400f0ce76cf4880603be1d5319 and now it runs on JDK 11. 🎉
