### ISSUE TITLE
Staging repository initialization hangs for 10+ minutes even with configured timeout

### ISSUE THREAD

**Issue by szpak** [gradle-nexus/publish-plugin#17]
Playing with the repository transitioning support I came accross the situation where `initializeSonatypeStagingRepository` hangs for 10+ minutes (I didn't wait much longer), even though a read timeout is by default set to 1 minute. I checked values at the comment the client is created and properly read from the plugin extension. Timeout related code in `NexusClient` also looks ok. Probably there was something wrong with the Sonatype server (I was able to reproduce it multiple times within an hour), but anyway it would be good to have timeout working. Leaving it have for further examination why okhttp3 behaved that way.

OpenJDK 11.0.5 and 13.0.1, Linux.

```
nexusPublishing {
    repositories {
        sonatype {
           stagingProfileId = "..."
        }
    }
    clientTimeout = Duration.ofSeconds(90)
}
```

```
> Task :initializeSonatypeStagingRepository
Caching disabled for task ':initializeSonatypeStagingRepository' because:
  Build cache is disabled
Task ':initializeSonatypeStagingRepository' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Creating staging repository for stagingProfileId '248647f1a45ed6'
<========-----> 66% EXECUTING [7m 51s]
> :initializeSonatypeStagingRepository
```
(fetching the staging profile takes just a moment, if profile is not configured)

```
"Execution worker for ':'" #911 prio=5 os_prio=0 cpu=201,83ms elapsed=254,27s tid=0x00007ff1e02cc800 nid=0xfd43 in Object.wait()  [0x00007ff2a036b000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@13.0.1/Native Method)
        - waiting on <no object reference available>
        at java.lang.Object.wait(java.base@13.0.1/Object.java:326)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http2.Http2Stream.waitForIo(Http2Stream.java:660)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:151)
        - locked <0x00000000eb526b08> (a io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http2.Http2Stream)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at io.github.gradlenexus.publishplugin.internal.NexusClient$1.intercept(NexusClient.kt:53)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at io.github.gradle-nexus.nexus.shadow.okhttp3.RealCall.execute(RealCall.java:81)
        at io.github.gradle-nexus.nexus.shadow.retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
        at io.github.gradlenexus.publishplugin.internal.NexusClient.createStagingRepository(NexusClient.kt:85)
        at io.github.gradlenexus.publishplugin.InitializeNexusStagingRepository$createStagingRepo$1.apply(InitializeNexusStagingRepository.kt:60)
        at io.github.gradlenexus.publishplugin.InitializeNexusStagingRepository$createStagingRepo$1.apply(InitializeNexusStagingRepository.kt:34)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(java.base@13.0.1/ConcurrentHashMap.java:1705)
        - locked <0x00000000eca64490> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
        at io.github.gradlenexus.publishplugin.InitializeNexusStagingRepository.createStagingRepo$gradle_nexus_publish_plugin(InitializeNexusStagingRepository.kt:56)
        at io.github.gradlenexus.publishplugin.InitializeNexusStagingRepository.createStagingRepoAndReplacePublishingRepoUrl(InitializeNexusStagingRepository.kt:51)
...
```

**Comment by szpak** [comment]
Ehh, a flash of inspiration always comes a moment after it is sent (even gave myself a few hours of other activities to think about that).

There is the fourth kind of timeout in httpok3 - `callTimeout`. When set, the execution is aborted.
From JavaDoc:
```
     * <p>The call timeout spans the entire call: resolving DNS, connecting, writing the request
     * body, server processing, and reading the response body. If the call requires redirects or
     * retries all must complete within one timeout period.
```

Nevertheless, from the stacktrace okhttp3 was waiting on read, so I would expect `readTimeout` to cover that...
```
at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http2.Http2Stream.waitForIo(Http2Stream.java:660)
at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:151)
- locked <0x00000000eb526b08> (a io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http2.Http2Stream)
at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
at io.github.gradle-nexus.nexus.shadow.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
```

**Comment by eli-darkly** [comment]
I'm also seeing the initializeSonatypeStagingRepository step hang for many minutes. The timeout parameter works for me, but I'm still suspicious that something might be wrong that isn't just on Sonatype's end, because I can see in the Sonatype UI that the repository actually did get created in less than a minute.

**Comment by szpak** [comment]
Closing as it seems to be better with the second instance of Sonatype Nexus
