### ISSUE TITLE
 Event: Failed: Profile target matcher or Staging repository is not in desired state

### ISSUE THREAD

**Issue by duraivelBP90** [gradle-nexus/publish-plugin#261]
Hi, I'm trying to close the repository and release it, where I;m getting this error "Event: Failed: Profile target matcher - profile-target-matching-staging"

Nexus repository manager : staging profiles screenshot
<img width="1440" alt="Screenshot 2023-08-17 at 8 18 33 AM" src="https://github.com/gradle-nexus/publish-plugin/assets/106576980/ac3074b7-43e7-4ae2-b5a9-005e5ac5c047">

Nexus staging repository error screenshot
<img width="1437" alt="Screenshot 2023-08-16 at 4 14 58 PM" src="https://github.com/gradle-nexus/publish-plugin/assets/106576980/05f9d284-216b-41eb-846a-732bf4c490a9">

Screenshot while I;m run in the terminal,
<img width="1168" alt="Screenshot 2023-08-16 at 5 51 10 PM" src="https://github.com/gradle-nexus/publish-plugin/assets/106576980/8d314fd9-bf44-42a0-ac1f-bffc65e0da0b">

**Comment by szpak** [comment]
It seems those files doesn't correspond to the group you are permitted to publish to. See also https://issues.sonatype.org/browse/OSSRH-70341 or https://issues.sonatype.org/browse/OSSRH-48197 . You need to fix JAR building (you can examine the generated package with `gw build` and looking into `build/libs` directory, without publishing).

Btw, it is completely not related to the plugin.

**Comment by duraivelBP90** [comment]
My GroupID is : com.oustme

And I can able to see that in the staging repositories and while build the app, I;m added the group as com.oustme

So, I;m not sure what is the issue with the group?

**Comment by szpak** [comment]
Those files (paths) looks strange. Do you really need them in the archive? Have you been able to publish the project manually in the past?

**Comment by duraivelBP90** [comment]
No, this is my first release to maven, I have followed the steps mentioned in this document : https://central.sonatype.org/publish/publish-guide/

**Comment by szpak** [comment]
I propose to run `gw build` (or `./gradlew build`), examine the produced JAR and think what would you like to publish. What is `34858478c42fac`? IS that directory available in your JAR?

**Comment by duraivelBP90** [comment]
Hi, I will run the above command, in the mean time, the 34858478c42fac is the staging repository available in the nexus repository manager.

Have a look at this screenshot : 
<img width="1412" alt="Screenshot 2023-08-17 at 2 33 01 PM" src="https://github.com/gradle-nexus/publish-plugin/assets/106576980/28e3e421-011a-43ed-96df-4df05403f7cb">

**Comment by szpak** [comment]
After `./gradlew build` please take a look into the JAR in: `build/libs`. What files/directories are included there?

**Comment by duraivelBP90** [comment]
Hi, in the generated jar file, contains path of com/oustme/oustsdk


Where, I can able to see all the contents,

<img width="764" alt="Screenshot 2023-08-17 at 3 45 34 PM" src="https://github.com/gradle-nexus/publish-plugin/assets/106576980/dd90bd4e-475c-46f5-94a6-377f94fdfd10">

**Comment by szpak** [comment]
If those paths:
![image](https://github.com/gradle-nexus/publish-plugin/assets/148013/6a16ad57-dfc2-4081-aa4c-0ba513607f71)

are not available in your JAR, then I don't know why Nexus complains about them. This plugin - in general - only works with a staging repository in Nexus - artifact build and uploading is done outside (by the maven-publish plugin & co).

You can try to publish your JAR manually without this plugin to verify it. You can also repo it in Sonatype's Jira, but first, I would recommend check if those path aren't somehow published there.

Btw, what Gradle version do you use? In the past, there is a problem with sha256 and sha512 checksums in Nexus. However, it was years ago.

**Comment by szpak** [comment]
Btw, I wonder if `outsSDK` instrad of `outssdk` might also be a problem?

**Comment by duraivelBP90** [comment]
I have tried with small case : oustsdk, but still the build is failing with the same error.
<img width="1260" alt="Screenshot 2023-08-17 at 4 44 59 PM" src="https://github.com/gradle-nexus/publish-plugin/assets/106576980/7197a64d-22d0-4320-9758-81e68257f15d">


And, I;m using the following things, 
The Gradle version : gradle-7.4.2
SHA : when I create the public key by using 4096

**Comment by szpak** [comment]
`Profile target mismatch` - https://issues.sonatype.org/browse/OSSRH-65994?focusedId=1032285&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1032285 ?

Maybe you have problem with the group ID? You can try to publish artifacts to Nexus (just publish, without using the staging repository features) and see what files are uploaded and with what path. `/34858478c42fac/` - as I already mentioned -l ooks strange.

**Comment by duraivelBP90** [comment]
Hi, thanks for the info, the same I found after I sent you the earlier comment. I was suppose to use com.oustme not the artefact id.


And, I can able to close the staging repository, but I;m getting this error while releasing it. Eventhough I can't able to see the build comoustme-1008 in the nexus repository manager.

"Releasing staging repository with id 'comoustme-1008'
Current staging repository status: state: closed, transitioning: true
Attempt 1/61 failed with result: StagingRepository(id=comoustme-1008, state=closed, transitioning=true)
Current staging repository status: state: closed, transitioning: true
Attempt 2/61 failed with result: StagingRepository(id=comoustme-1008, state=closed, transitioning=true)

Expiring Daemon because JVM heap space is exhausted
Daemon will be stopped at the end of the build after running out of JVM memory
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Exception in thread "Thread-399" java.lang.OutOfMemoryError: Java heap space
        at io.github.gradlenexus.publishplugin.shadow.okhttp3.internal.http2.Http2Connection.close(Http2Connection.java:481)
        at io.github.gradlenexus.publishplugin.shadow.okhttp3.internal.http2.Http2Connection$ReaderRunnable.execute(Http2Connection.java:677)
        at io.github.gradlenexus.publishplugin.shadow.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.base/java.lang.Thread.run(Thread.java:1589)

> Task :releaseSonatypeStagingRepository
Current staging repository status: state: not_found, transitioning: false
Repository with id 'comoustme-1008' effectively released
:releaseSonatypeStagingRepository (Thread[#543,included builds,5,main]) completed. Took 6 mins 34.473 secs.
:closeAndReleaseSonatypeStagingRepository (Thread[#547,Execution worker for ':' Thread 4,5,main]) started.

> Task :closeAndReleaseSonatypeStagingRepository
Skipping task ':closeAndReleaseSonatypeStagingRepository' as it has no actions.
:closeAndReleaseSonatypeStagingRepository (Thread[#547,Execution worker for ':' Thread 4,5,main]) completed. Took 0.006 secs.
producer locations for task group 0 (Thread[#547,Execution worker for ':' Thread 4,5,main]) started.
producer locations for task group 0 (Thread[#547,Execution worker for ':' Thread 4,5,main]) completed. Took 0.0 secs.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 8m 50s
35 actionable tasks: 7 executed, 28 up-to-date
Watched directory hierarchies: [/Users/duraivel/AndroidStudioProjects/oustSDK]
Expiring Daemon because JVM heap space is exhausted
"

Attaching the screenshot for this, 
<img width="1171" alt="Screenshot 2023-08-17 at 5 14 04 PM" src="https://github.com/gradle-nexus/publish-plugin/assets/106576980/7c10273b-c16b-4869-ba25-4701fcf2698e">

**Comment by duraivelBP90** [comment]
Thanks for the prompt response, now I can able to successfully release the build

**Comment by szpak** [comment]
> Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/com/oustme/oustsdk/2.10.1.14/oustsdk-2.10.1.14.aar'

Probably you wanted to release the same version twice or re-uploaded the same artifacts twice to the same staging repository.

**Comment by szpak** [comment]
> Exception in thread "Thread-399" java.lang.OutOfMemoryError: Java heap space
at io.github.gradlenexus.publishplugin.shadow.okhttp3.internal.http2.Http2Connection.close(Http2Connection.java:481)

Probably you could stop the Gradle deamon `gw --stop` and try again

**Comment by szpak** [comment]
> Thanks for the prompt response, now I can able to successfully release the build

Cool, I could read all the messages before answering :).

Btw, you could write what was the problem(s) in your case, for people hitting this issue from the web search engine.

**Comment by prdoyle** [comment]
@duraivelBP90 - I'm hitting this now and I'd love to know how you fixed it.
