### ISSUE TITLE
"uses configured connect timeout" test fails on Fedora 30

### ISSUE THREAD

**Issue by szpak** [gradle-nexus/publish-plugin#8]
The `uses configured connect timeout` test fails with:
```
java.lang.AssertionError: 
Expecting:
 <"> Task :initializeMyNexusStagingRepository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
task ':initializeMyNexusStagingRepository' exceeded its timeout

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleException: task ':initializeMyNexusStagingRepository' exceeded its timeout
	at org.gradle.api.internal.tasks.TaskStateInternal.setAborted(TaskStateInternal.java:70)
	at org.gradle.api.internal.tasks.execution.TimeoutTaskExecuter.executeWithTimeout(TimeoutTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.TimeoutTaskExecuter.execute(TimeoutTaskExecuter.java:50)
```
every time I execute it on my Fedora 30 box with Java 11. Verified with Gradle 5.0 and 5.6.

The IP is not non-routable on my system :)
```
$ telnet 10.255.255.1 80
Trying 10.255.255.1...
Connected to 10.255.255.1.
Escape character is '^]'.
```

It's rather specific to my system (VPN routing rules?), but reported to remember about that.

**Comment by vlsi** [comment]
Just in case, pgjdbc has the same IP: https://github.com/pgjdbc/pgjdbc/blob/08d81291c69d02d8973d6b39dac82bdaad91f2ee/pgjdbc/src/test/java/org/postgresql/test/jdbc2/ConnectTimeoutTest.java#L24-L25

Just in case, there's https://github.com/NetCrusherOrg/netcrusher-java that might help to inject the required failures
